/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./auth/**/*.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Core Design Colors
        surface: "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#44474c",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        outline: "#75777c",
        "outline-variant": "#c5c6cc",
        "surface-tint": "#555f6f",
        primary: "#0a1422",
        "on-primary": "#ffffff",
        "primary-container": "#1f2937",
        "on-primary-container": "#8690a1",
        "inverse-primary": "#bdc7d9",
        secondary: "#446900",
        "on-secondary": "#ffffff",
        "secondary-container": "#b2f746",
        "on-secondary-container": "#496f00",
        tertiary: "#121515",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#272929",
        "on-tertiary-container": "#8f9090",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d9e3f6",
        "primary-fixed-dim": "#bdc7d9",
        "on-primary-fixed": "#121c2a",
        "on-primary-fixed-variant": "#3d4756",
        "secondary-fixed": "#b2f746",
        "secondary-fixed-dim": "#98da27",
        "on-secondary-fixed": "#121f00",
        "on-secondary-fixed-variant": "#334f00",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        background: "#f8f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e1e2e4",
        "success-green": "#16A34A",
        "error-red": "#EF4444",
        "text-muted": "#6B7280",
        "border-subtle": "#F1F5F9",

        // Legacy colors to maintain compatibility
        wallet: {
          charcoal: "#1F2937",
          lime: "#A3E635",
          softgray: "#F3F4F6",
        },
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "card-padding": "1.25rem",
        "safe-area-bottom": "7rem",
        "section-gap": "1.5rem",
        "navbar-height": "4.5rem",
        "container-max": "1024px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "500" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-xl": [
          "36px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg": ["20px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
